name: Flutter Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release, develop, 'feature/**' ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependencies
        run: flutter pub get

      - name: Test flutter app
        run: flutter test